---
title: "Home Work 2"
author: "Quinhas Fernandes"
date: "10/9/2017"
output:
  html_document: default
  word_document: default
---

```{r, warning =FALSE}
library(gapminder)
library(ggplot2)
library(dplyr)
data("gapminder")
```

str(gapminder)

```{r}
ggplot(data = gapminder, aes(x = year, y = lifeExp, group = continent, color = continent)) +
  geom_smooth(method=lm) + facet_wrap( ~ continent) +
  xlab("Year") + ylab("Life expectancy (yr)") +
  ggtitle("Global trends in Life expectancy between 1950-2000") + theme_bw()
````




```{r}
new.object <- Africa

Africa <- gapminder %>% filter(continent == "Africa")
head(Africa)

ggplot(data = Africa, aes(x = year, y = lifeExp, color = continent)) +
  geom_smooth(method=lm) + facet_wrap( ~ continent) +
  xlab("Year") + ylab("Life expectancy") +
  ggtitle("Africa Trends in Life expectancy over time") + theme_bw()
```


```{r}
new.object <- Mozambique

Mozambique <- gapminder %>% filter(country == "Mozambique")
head(Mozambique, 6)

ggplot(data = Mozambique, aes(x = year, y = lifeExp)) +
  geom_smooth(method=lm) + 
  xlab("Year") + ylab("Life expectancy") +
  ggtitle("Life expectancy in Mozambique") +
  theme_bw()
````

```{r}
ggplot(data = Mozambique, aes(x = pop, y = lifeExp)) +
  geom_jitter(height = 0.5, width = 2) + 
  ylim(30, 55)
  xlab("Population") + ylab("Life expectancy (yr)") +
  ggtitle("Relation between Life Expetancy and  ") +
  theme_bw()
````


```{r}
ggplot(data = Mozambique, aes(x = gdpPercap, y = lifeExp, color = continent)) +
  geom_jitter(height = 2, width = 3) + 
  ylim(30, 55)+
  xlim(300, 900) +
  xlab("GDP percap (usd)") + ylab("Life expectancy (yr)") +
  ggtitle("Relation between Life Expetancy and GDP Percapita in Mozambique ") +
  theme_bw()
````




